api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity', '%kernel.project_dir%/src/Filter']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    eager_loading:
        max_joins: 1000
    validator:
        serialize_payload_fields: [severity]
#    collection:
#        exists_parameter_name: 'not_null'